### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by cron410** [wsgcsysadmin/syncthing-tools#1]
Keep getting HTTP error 401 not authorized. Does this script still work for newer versions of syncthing?

command line:
./set-st-bw.py -x remotehost -r 0 -c ./set-st-bw.conf

config file:
[remotehost]
url=https://myusername:secretpass@192.168.1.15:8384
apikey=gdko0PfvqNl6h7Mn41mX-k6UZPDmjpEu
insecure=True

**Comment by wsgcsysadmin** [comment]
The latest versions of Syncthing are suported. 

The 401 error means that the HTTP authentication failed. Check the user name and password you have set in the configuration file.  Can you log in to the URL with your browser  using the same credentials?

Do not use special characters like "@", "%", or ":" in the user name or password. I will have to handle those better.

**Comment by cron410** [comment]
Username has no special chars, password does. I set up remote access to the
web gui by changing the listening address to 0.0.0.0:8384 in syncthing
because its installed on a windows server. Im running this script from a
linux server over the LAN. I am able to log into syncthing with the same
credentials on 3rd computer with an Incognito session in chrome. When
changing settings, I briefly got the same 401 error in the Synctrayzor gui
on the windows server. After restarting synctraysor and syncthing, the
error went away, but i still get it on the linux server. I have the api key
set and i manually verified each character. My next step is to manually
type the api key to see if copying from chrome and pasting into a puTTY
session is causing special characters or something. I have tried toggling
the secure tag in the script config file, but it just spews SSL errors
which is to be expected.

Sent from mobile.

Edit: I skipped over the part where I cannot use special chars in the password either. Not a big deal for me, I just locked down the firewall for that port so only the linux server can access it. I'll change the password to something simple and test. Other users might not like needing a simple password so you might want to work on that. I do plan to post this to several threads on the syncthing forum because it would definitely be useful.

**Comment by cron410** [comment]
After chaning the password to a simple password with no special chars, no numbers, it still says unable to retrieve config HTTP 401.

**Comment by wsgcsysadmin** [comment]
If you have CURL installed on your Linux machine try this:
curl  -s  -v --user USERNAME:PASSWORD --insecure https://192.168.1.15:8384/rest/system/config

It should return a dump of the server's configuration that starts with "{"version":11" or say "Not authorized".

Also FYI I've updated the script to break out the user name and password from the url in the configuration file.

**Comment by cron410** [comment]
The curl command works! I can see the apikey and other setting. Lots of
positive statuses coming back. Ill try the new script later.

**Comment by cron410** [comment]
Updated the script and config file. Now I am getting a 403 error. Unable to update config. CSRF Error

Still the same after restarting syncthing. It looks like CSRF protection was added back in early 2014, so this is not a new feature. https://github.com/syncthing/syncthing/issues/287

**Comment by wsgcsysadmin** [comment]
I will require the following to continue working on this:
Version of the Syncthing server (from the About option in the web interface)
OS version of the Syncthing server
OS version of the Linux machine 
Output from this command on Linux machine: python -V
Output from this command on Linux machine: python -c "import requests; print requests.**version**"

**Comment by cron410** [comment]
Sorry it took so long to get back with you, the email notification was buried :/

Server 2012r2
Debian 7 Kernel 3.16
Python 2.7.3

``` python
$ python -c "import requests; print requests.version"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
```

``` python
$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> print requests.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
```

**Comment by wsgcsysadmin** [comment]
Could you try again with the latest code?
